version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-homeweb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=homeweb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - emptyvolume:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    ports:
      - 8000:8080
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      
  
volumes: 
  emptyvolume: